services:
  app:
    image: localhost/reddit-crawler:latest
    container_name: reddit-crawler-app
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?options=-c%20timezone%3DUTC
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${PORT}:${PORT}"
    networks:
      - crawlers-network
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - reddit_logs:/app/logs:Z
    healthcheck:
      test: ["CMD-SHELL", "/bin/sh -c 'ss -ltn | grep -q :${PORT}'"]
      interval: 10s
      timeout: 5s
      retries: 6

networks:
  crawlers-network:
    external: true

volumes:
  reddit_logs:
